name: Build and push to site

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 16.x
            - name: install yarn
              run: npm i -g yarn
            - name: run yarn
              run: yarn
            - name: build release
              run: cat package.json
            - name: create distribution
              run: yarn upload
              env:
                  ENDPOINT: ${{ secrets.ENDPOINT }}
